title: Audhi Aprilliant
author: audhi
subtitle: Unlock the power of data

url: "https://audhiaprilliant.github.io/"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "© 2026 Audhi Aprilliant powered by Jekyll"

profile-picture: assets/images/avatar.png
favicon_location: assets/images/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: ""
 - name: "Blog"
   link: "blog/"
 - name: "Reading"
   link: "books"